### ISSUE TITLE
Build fails with latest Haskell platform

### ISSUE THREAD

**Issue by wyager** [markhibberd/riak-haskell-client#24]
Running `cabal install riak` leads to 

    Text/ProtocolBuffers/Identifiers.hs:124:24:
    Ambiguous occurrence ‘uncons’
    It could refer to either ‘Text.ProtocolBuffers.Identifiers.uncons’,
                             defined at Text/ProtocolBuffers/Identifiers.hs:103:3
                          or ‘Data.List.uncons’,
                             imported from ‘Data.List’ at Text/ProtocolBuffers/Identifiers.hs:33:1-16
                             (and originally defined in ‘GHC.List’)

while `Building protocol-buffers-fork-2.0.16`.

**Comment by tmcgilchrist** [comment]
That looks like an issue with `protocol-buffers-fork-2.0.16` that was released recently, rather than with `riak-haskell-client` itself. I'm looking into reproducing it, once I sort out `darcs` and get it installed.

I've reached out to the maintainer of that package, letting him know about the issues.

Thanks for reporting it.

**Comment by tmcgilchrist** [comment]
Just out of interest could you run `cabal --version`, `ghc --version`, `cabal sandbox hc-pkg list` and `ghc-pkg list` to see what versions of packages you've got?

**Comment by wyager** [comment]
Sure! https://gist.github.com/wyager/dbafdfec678d45866768

**Comment by tmcgilchrist** [comment]
New version 0.9.0.0 released onto Hackage, should fix this issue. Please test it out and let us know.
